# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :setup do
  setup_project
end

private_lane :setup_project do
  create_keychain(
    name: "tech_at_safepaths_keychain",
    password: "meow",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
end


lane :beta do
platform :ios do

    desc "Push a new beta build to TestFlight"
    # # Ensure that your git status is not dirty
    # ensure_git_status_clean
    lane :build do

    APP_ID = "org.pathcheck.covid-safepaths"
    PROFILE = "match AppStore org.pathcheck.covid-safepaths"
    # TEAM = "79Z8HUPGC3"
    SCHEME = "COVIDSafePaths"
    WORKSPACE = "COVIDSafePaths.xcworkspace"
    # PLIST_PATH = "COVIDSafePaths/Info.plist"

    signing_bundle_details = {
      :BUNDLE_IDENTIFIER => APP_ID,
      :PROVISIONING_PROFILE_SPECIFIER => PROFILE,
      :DEVELOPMENT_TEAM => TEAM
    }

    match(
      readonly: true,
      keychain_name: "tech_at_safepaths_keychain",
      keychain_password: "meow",
      profile: PROFILE
    )

    build_ios_app(
      workspace: WORKSPACE,
      scheme: SCHEME,
      configuration: "Release",
      silent: true,
      clean: true,
    )


    # # Increment the build number (not the version number)
    # # Providing the xcodeproj is optional
    # increment_build_number(xcodeproj: "Example.xcodeproj")

    # # Commit the version bump
    # commit_version_bump(xcodeproj: "Example.xcodeproj")

    # # Add a git tag for this build. This will automatically
    # # use an appropriate git tag name
    # add_git_tag

    # # Push the new commit and tag back to your git remote
    # push_to_git_remote

      # upload_to_testflight
  end
end

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   # # Ensure that your git status is not dirty
#   # ensure_git_status_clean

#   # # Increment the build number (not the version number)
#   # # Providing the xcodeproj is optional
#   # increment_build_number(xcodeproj: "Example.xcodeproj")

#   # # Commit the version bump
#   # commit_version_bump(xcodeproj: "Example.xcodeproj")

#   # # Add a git tag for this build. This will automatically
#   # # use an appropriate git tag name
#   # add_git_tag

#   # # Push the new commit and tag back to your git remote
#   # push_to_git_remote

#   lane :beta do
#     build_app(workspace: "COVIDSafePaths.xcworkspace", scheme: "COVIDSafePaths")
#     upload_to_testflight
#   end
# end