# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs Android (Native) unit tests"
  lane :test do
    gradle(task: "test")
  end

  JS_PACKAGE = load_json(json_path: "../package.json")

  desc "Build a Beta APK and AAB"
  lane :beta do

    increment_version_code(
      gradle_file_path: "../android/app/build.gradle",
    )

    increment_version_name(
      gradle_file_path: "../android/app/build.gradle",
      version_name: JS_PACKAGE['version']
    )

    gradle(
      task: "assembleRelease",
      print_command: false,
      properties: {
        ENV["secrets.SIGNING_KEY"] => "keystore.jks",
        ENV["secrets.KEY_ALIAS"] => "key_alias",
        ENV["secrets.KEY_STORE_PASSWORD"] => "store_password",
        ENV["secrets.KEY_PASSWORD"] => "key_password"
      }
    )

    gradle(
      task: "bundleRelease",
      print_command: false,
      properties: {
        ENV["secrets.SIGNING_KEY"] => "keystore.jks",
        ENV["secrets.KEY_ALIAS"] => "key_alias",
        ENV["secrets.KEY_STORE_PASSWORD"] => "store_password",
        ENV["secrets.KEY_PASSWORD"] => "key_password"
      }
    )

    APK_PATH = "android/app/build/outputs/apk/release/app-release-unsigned-signed.apk"
    AAB_PATH = "android/app/build/outputs/bundle/release/app.aab"


    # upload_to_play_store(
    #   track: 'beta',
    #   json_key_data: ENV["secrets.GOOGLE_PLAY_STORE_SECRET"],
    #   aab: AAB_PATH
    #   version_code: '1.1.0'
    # )

    # slack(message: 'Successfully distributed a new beta build')
  end
end
