on:
  push:

jobs:
  deploy_ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master

      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Cache node_modules/
        uses: actions/cache@v1
        id: node_cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - name: Install Node Dependencies
        if: steps.node_cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Cache ruby gems
        uses: actions/cache@v1
        id: ruby_cache
        with:
          path: ios/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby Dependencies
        if: steps.ruby_cache.outputs.cache-hit != 'true'
        run: | 
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: ./ios

      - name: Cache CocoaPods
        uses: actions/cache@v1
        id: cocoapods_cache
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-

      - name: Install Cocoapods
        if: steps.cocoapods_cache.outputs.cache-hit != 'true'
        run: pod install --repo-update
        working-directory: ./ios

      - name: Setup Match Keychain
        uses: maierj/fastlane-action@v1.4.0
        env:
          # MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.APPLE_APP_STORE_SECRET }}
          # SIGNING_ID: ${{ secrets.SIGNING_ID }}
          # APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          # TEAM_ID: ${{ secrets.TEAM_ID }}
        with:
          lane: 'setup'
          subdirectory: 'ios'
          bundle-install-path: 'vendor/bundle'

      - name: Build ios Beta artifact
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'beta'
          subdirectory: 'ios'
          bundle-install-path: 'vendor/bundle'